# Generated by Django 3.2.5 on 2024-07-23 11:30

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240717_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
