# version: '3.5'
services:
  auth-service:
    build: ./services/AuthenticationService
    volumes:
      - ./services/AuthenticationService:/usr/src/app
      - media_volume:/var/www/transcendence/media
      - ssl_cert_volume:/etc/ssl/certs:ro
    ports:
      - "8000:8000"
    environment:
      PGPASSWORD: ${PGPASSWORD} # TODO : docker secret ?
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      CLIENT_UID_42: ${CLIENT_UID_42}
      CLIENT_SECRET_42: ${CLIENT_SECRET_42}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    depends_on:
      - db
      - game-service
    restart: on-failure:3

  game-service:
    build: ./services/GameService
    volumes:
      - ./services/GameService:/usr/src/app
      - ssl_cert_volume:/etc/ssl/certs
    ports:
      - "8001:8001"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    depends_on:
      - db
    restart: on-failure:3

  db: # TODO : ssl 
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}

  tchat:
    build: ./services/Tchat
    ports:
      - "8002:8002"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    restart: unless-stopped
    volumes:
      - ./services/Tchat:/usr/src/app
      - ssl_cert_volume:/etc/ssl/certs:ro
    depends_on:
      - db
      - game-service
  
  ui-service:
    build: ./services/UserInterface
    volumes:
      - ./services/UserInterface:/usr/src/app
      - ssl_cert_volume:/etc/ssl/certs:ro
    ports:
      - "8003:8003"
    environment:
      OAUTH_LINK: ${OAUTH_LINK}
    depends_on:
      - db
      - game-service
    restart: on-failure:3

volumes:
  media_volume:
  ssl_cert_volume: